export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const FORM_BUTTON_TOGGLE = "FORM_BUTTON_TOGGLE";
export const RESET = "RESET";
